### ISSUE TITLE
XSS & tests

### ISSUE THREAD

**Issue by jamescostian** [dosyago-coder-0/brutal.js#1]
Hi! I think this is a neat idea, and I'm definitely fascinated by it. One thing someone pointed out was that [it has an XSS vulnerability](https://news.ycombinator.com/item?id=17484478). Normally I'd just send you a PR to fix that and include a test so that you can see that without the PR, it has the vuln, and with the PR, it does not. But I noticed you don't have any tests ☹️. I'd be fine with writing some tests for this, but I'd like to know how you'd like to go about testing this. Do you want to use something like [jsdom](https://github.com/jsdom/jsdom) or do you want to use a real browser? What do you want to write your tests with - [tape](https://github.com/substack/tape), [jest](https://github.com/facebook/jest), [mocha](https://github.com/mochajs/mocha) or what?

**Comment by dosyago-coder-0** [comment]
Tests are a good idea, I'd like to use tape and a real browser. I really appreciate you offering to submit an XSS fix PR. Please go ahead and I look forward to reading it.

**Comment by franciscop** [comment]
Thanks for opening the issue, @jamescostian. I am the one who commented on HN and was going to open it now. XSS is quite complex in this situation, having to balance between usability and safety; basically if you want this to work (plain string), you'd have to make it insecure by default:

```js
const Button = () => `<button>Hello!</button>`;
```

See [a bit of the rationale](https://news.ycombinator.com/item?id=17487112) (for lit-html, but it seems fitting):

Does it throw if a template returns a string? While it's a cool feature to be able to do this, it's also quite dangerous (specially when dealing with beginners for this library) to have these two behaving almost the same but one being safe and the other not:

```js
// Safe version
const header = title => html`<h1>${title}</h1>`;

// Unsafe version, but it "works" as expected
const header = title => `<h1>${title}</h1>`;
```

I do not want a single optional character to be separating me from XSS. I do not think that's a good idea, and neither the guys at React since their way of injecting unsecure HTML is `dangerouslySetInnerHTML` instead of something like an extra `{`.

**Comment by jamescostian** [comment]
@franciscop thank you for bringing it up! But don't worry, if you use the unsafe version it actually doesn't work. With the unsafe version, `header` is a string. When you try to render that string using this library, [the code](https://github.com/dosyago-coder-0/brutal.js/blob/master/r.js#L92-L96) will throw because (after skipping over the body of the first if statement), the string would have to be destructured into `{str,handlers}`, but a string does not have a `str` property, nor does it have a `handlers` property.

Thus, they are both safe.

**Comment by jamescostian** [comment]
@dosyago-coder-0 I made a PR - #3 - for the XSS protection. I don't actually have enough time to setup tests, though - sorry.

I'm going to close this issue since the XSS vulnerability will be addressed by that pull request.
